const titles = [
    "Exploring the Cosmos", "Mastering JavaScript", "The Art of Cooking", "Travel Tips for Europe", "Understanding AI",
    "History of the Roman Empire", "Gardening Basics", "Advanced CSS Techniques", "Digital Photography 101", "Healthy Living Guide",
    "Top 10 Movie Classics", "Building a Home Gym", "The Future of Technology", "Yoga for Beginners", "World War II Overview",
    "Cryptocurrency Explained", "Wildlife Conservation", "Effective Communication Skills", "Top 10 Travel Destinations", "Meditation Practices",
    "The Science of Climate Change", "Learning Python", "Art History Essentials", "Astronomy for Amateurs", "Fitness and Nutrition",
    "Guide to Minimalism", "Home Renovation Tips", "Social Media Strategies", "Hiking and Camping Tips", "Basics of Blockchain",
    "History of Art", "Understanding Quantum Physics", "Investing for Beginners", "Culinary Techniques", "Mental Health Awareness",
    "Music Theory Basics", "Photography Tips and Tricks", "Introduction to Philosophy", "Cooking Healthy Meals", "Modern Web Design",
    "Public Speaking Skills", "Top 10 Music Genres", "Sustainable Living", "Learning HTML and CSS", "DIY Home Projects",
    "Space Exploration Milestones", "The Psychology of Happiness", "Top 10 Famous Paintings", "Effective Study Habits", "Pet Care Tips",
    "The Rise of E-commerce", "Mindfulness Meditation", "Ancient Civilizations", "Mastering Public Speaking", "Gardening for Beginners",
    "The Future of Work", "Personal Finance Tips", "Classic Literature", "Green Energy Solutions", "Science Fiction Essentials",
    "Healthy Eating Habits", "Building an Online Business", "Understanding Human Anatomy", "Film Making Basics", "Exploring National Parks",
    "History of Mathematics", "Robotics and Automation", "Cooking with Herbs", "Ethical Hacking Guide", "Interior Design Tips",
    "The World of Fashion", "Mental Wellness Practices", "Graphic Design Fundamentals", "Creative Writing Tips", "Exploring Local Cultures",
    "History of the Internet", "The Power of Positive Thinking", "Wildlife Photography", "Financial Planning Guide", "Space Science for Kids",
    "Developing Leadership Skills", "The History of Music", "Understanding Genetics", "Effective Parenting Tips", "The Art of Storytelling",
    "Renewable Energy Sources", "Digital Marketing Strategies", "The World of Microbiology", "Traveling on a Budget", "Top 10 Historical Events",
    "The Basics of Networking", "Exploring World Cuisine", "Improving Memory Skills", "Astronomy Facts", "Personal Growth Techniques",
    "The World of Animation", "History of Modern Art", "The Science of Nutrition", "Web Development Trends", "Exploring World Religions"
  ];